const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'TANTRA Execution Service API',
      version: '1.0.0',
      description: 'Execution Runtime Service for the TANTRA Gated Bridge Infrastructure.',
      contact: {
        name: 'TANTRA Infrastructure',
      },
    },
    servers: [
      {
        url: 'http://localhost:3003',
        description: 'Local development server',
      },
    ],
    components: {
      securitySchemes: {
        BridgeSignature: {
          type: 'apiKey',
          in: 'body',
          name: 'bridge_signature',
          description: 'JWT token issued by Sarathi Authority, passed as bridge_signature in request body. Format: Bearer <jwt>',
        },
      },
      schemas: {
        HealthResponse: {
          type: 'object',
          properties: {
            service: {
              type: 'string',
              example: 'execution',
            },
            status: {
              type: 'string',
              example: 'healthy',
            },
            algorithms: {
              type: 'array',
              items: {
                type: 'string',
              },
              example: ['RS256', 'EdDSA'],
            },
          },
        },
        RunRequest: {
          type: 'object',
          required: ['workload', 'trace_id', 'execution_id', 'bridge_signature'],
          properties: {
            workload: {
              type: 'string',
              description: 'The workload to execute',
              example: 'my-processing-task',
            },
            trace_id: {
              type: 'string',
              format: 'uuid',
              description: 'Immutable trace identifier generated by Core',
              example: 'a71bf018-cde6-4ef2-bafe-b11de9ecd68b',
            },
            execution_id: {
              type: 'string',
              format: 'uuid',
              description: 'Immutable execution identifier generated by Core',
              example: 'c6e0eece-45d5-4cdc-bfc5-6c9c46ad4426',
            },
            bridge_signature: {
              type: 'string',
              description: 'JWT token from Sarathi Authority (Bearer <jwt>)',
              example: 'Bearer eyJhbGciOiJFZERTQSIs...',
            },
          },
        },
        RunResponse: {
          type: 'object',
          properties: {
            trace_id: {
              type: 'string',
              format: 'uuid',
              description: 'Immutable trace identifier',
            },
            execution_id: {
              type: 'string',
              format: 'uuid',
              description: 'Immutable execution identifier',
            },
            status: {
              type: 'string',
              enum: ['completed'],
              example: 'completed',
            },
            result: {
              type: 'object',
              description: 'Execution result payload',
              example: {
                workload: 'my-processing-task',
                output: 'Processed my-processing-task',
              },
            },
            artifact_location: {
              type: 'string',
              description: 'Location of stored artifact in Bucket',
              example: 'artifacts/a71bf018-cde6-4ef2-bafe-b11de9ecd68b/c6e0eece-45d5-4cdc-bfc5-6c9c46ad4426',
            },
            duration_ms: {
              type: 'integer',
              description: 'Execution duration in milliseconds',
              example: 100,
            },
          },
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            error: {
              type: 'string',
              description: 'Error message',
            },
            trace_id: {
              type: 'string',
              format: 'uuid',
            },
            execution_id: {
              type: 'string',
              format: 'uuid',
            },
          },
        },
      },
    },
  },
  apis: ['./app.js'],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
